# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[package]
name = "clap_config"
version = "0.1.0"

license.workspace=true
publish.workspace=true
keywords.workspace=true
categories.workspace=true
edition.workspace=true
repository.workspace=true
readme.workspace=true
authors.workspace=true

[lib]
proc-macro = true

[dev-dependencies]

[dependencies]
proc-macro2 = "1.0.71"
quote = "1.0.33"
syn = { version = "2.0.42", features = ["full"] } # Add "extra-traits" feature to debug.
